### ISSUE TITLE
When training for longer time (>7 hours) fails to save checkpoint

### ISSUE THREAD

**Issue by ddvladimir** [david-gpu/deep-makeover#3]
Progress[100%], ETA[   0m], Batch [145460], gene[0.203], disc[0.552] real[0.218] fake[0.334]
Traceback (most recent call last):
  File "dm_main.py", line 169, in <module>
    tf.app.run()
  File "/usr/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "dm_main.py", line 160, in main
    dm_train.train_model(train_data)
  File "/mnt/disk02/projects/deep-makeover_ftm/dm_train.py", line 132, in train_model
    _save_checkpoint(td, batch)
  File "/mnt/disk02/projects/deep-makeover_ftm/dm_train.py", line 68, in _save_checkpoint
    saver.save(td.sess, newname)
 File "/usr/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1386, in save
    self.export_meta_graph(meta_graph_filename)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1414, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2257, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2220, in _as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.

**Comment by david-gpu** [comment]
That is interesting. Some googling showed a potentially related issue: https://github.com/tensorflow/tensorflow/issues/2654

Have you tried any of the ideas in there?

**Comment by david-gpu** [comment]
OK, I think I know what is happening. Function `_save_image()` in `dm_train.py` is repeatedly adding new nodes to the graph.

While I fix that problem you could increase the value of `summary_period` so that this operation doesn't happen so frequently.

Let me know if that helps.

**Comment by david-gpu** [comment]
OK, so I switched `_save_image()` to use numpy instead of tensorflow. I think that should largely take care of the problem of ever-growing checkpoints.

Could you please try commit `c2ae55c..779100c` and let me know whether that helps?

**Comment by david-gpu** [comment]
Based on my testing the checkpoint size went down to ~20MB after 40K batches, so I'll be closing this issue.

Thanks for reporting it!

**Comment by ddvladimir** [comment]
I have also retested it after your update and it works fine now. 

Thank you for your help!
